version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: groweasy-frontend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000/api

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: groweasy-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    restart: unless-stopped